### ISSUE TITLE
MZG7PSYZWGXFJ6JVWYYZUSNZK4DCU2N16Z

### ISSUE THREAD

**Issue by Falehfaleh** [MicrosoftDocs/vsts-rest-api-specs#619]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6170afea-4a64-33d0-66fd-c6aed11c401f
* Version Independent ID: 4782ca92-bfc8-abeb-8f7b-98578d8e88e8
* Content: [Token Lifecycle Management REST API for Azure DevOps Services - Azure DevOps Services REST API](https://learn.microsoft.com/en-us/rest/api/azure/devops/tokens/?source=recommendations&tabs=powershell)
* Content Source: [docs-ref-conceptual/6.1/tokens/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/6.1/tokens/index.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **sergiikozak**
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/442
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/618
- [ ] https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/442
- [ ] https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/616
- [ ] https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/465
- [ ] https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/615
```

```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/618
- [ ] https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/617
- [ ] https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/465
- [ ] https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/613
- [ ] https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/442
```

```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/442
- [ ] https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/618
- [ ] https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/617
```

```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/615
```
